### ISSUE TITLE
Multi-Shot and Aimed Shot support

### ISSUE THREAD

**Issue by Dobskii** [raethkcj/YaHT#3]
Same as with the Steady shot castbar support, having multi and aimed also work would be amazing!

Should be under the Enhancement label

**Comment by raethkcj** [comment]
Latest version has Multi-Shot working using the Blizzard cast bar. I realized this was actually in the original addon, but I hadn't fixed it yet in the port. This will *mostly* fix Aimed Shot too, but I can't test because I don't have it on my Karazhan hunter yet.

The timer is working but the bar doesn't say the spell name for now. Will continue to work on it.

If you're using a castbar other than the default Blizzard one, unfortunately this won't show up there. I use Quartz for example, and it looks like I would need to manually check for Quartz and update that castbar too. This would have to be done for every additional castbar addon.

**Comment by raethkcj** [comment]
Multi and Aimed are both working correctly now. Aimed Shot and Steady Shot actually do work with all castbars in TBC by default. Multi-shot is the only one that needs a custom castbar, and that is working as well. All of the shots correctly pause the Auto Shot timer if you cast them at inappropriate times. Aimed Shot interrupts your Auto Shot even if you're drawing, and also resets the swing timer completely  when it finishes.
